@startuml
    left to right direction
    circle          Client
    class Singleton {
        - {static} instance: Singleton
        - Singleton()
        + getInstance(): Singleton
    }

    Client --> Singleton
    Singleton --> Singleton
@enduml